# Generated by Django 6.0.7 on 2026-09-07 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_linkedin_url_profile_mobile_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='custom_wallpaper',
            field=models.ImageField(blank=True, null=True, upload_to='wallpapers/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='onboarding_completed',
            field=models.BooleanField(default=False),
        ),
    ]
