# Generated by Django 6.0.7 on 2026-09-08 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_custom_wallpaper_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='color_preset',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='font_family',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='theme_mode',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='wallpaper',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='wallpaper_blur',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='wallpaper_opacity',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
