# Generated by Django 6.0.7 on 2026-09-08 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile_color_preset_profile_font_family_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='celebrations_enabled',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='dashboard_layout',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
