# Generated by Django 6.0.7 on 2026-09-10 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_profile_celebrations_enabled_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profilelink',
            options={'ordering': ['position', 'id']},
        ),
        migrations.AddField(
            model_name='profilelink',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
