# Generated by Django 6.0.7 on 2026-09-10 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_refinementnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='personal_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
