# Generated by Django 6.0.7 on 2026-09-10 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_profile_personal_email'),
        ('applications', '0019_application_waiting_and_historical'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='section_icons/'),
        ),
        migrations.AddField(
            model_name='education',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='section_icons/'),
        ),
        migrations.AddField(
            model_name='extracurricular',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='section_icons/'),
        ),
        migrations.AddField(
            model_name='profileaddress',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_addresses', to='applications.country'),
        ),
        migrations.AddField(
            model_name='profilelink',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='section_icons/'),
        ),
    ]
