# Generated by Django 6.0.7 on 2026-09-11 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_grant_developer_to_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='refinementnote',
            name='screens',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
