# Generated by Django 6.0.7 on 2026-09-11 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_refinement_ticket_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pinned_photo',
            field=models.ImageField(blank=True, null=True, upload_to='pinned/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='pinned_photo_caption',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
