# Generated by Django 6.0.7 on 2026-09-13 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_title_case_link_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='preferred_name',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
