# Generated by Django 6.0.7 on 2026-09-08 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='all_day',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='EventReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minutes_before', models.PositiveIntegerField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='events.calendarevent')),
            ],
            options={
                'ordering': ['minutes_before'],
                'constraints': [models.UniqueConstraint(fields=('event', 'minutes_before'), name='uniq_reminder_per_event')],
            },
        ),
    ]
