# Generated by Django 6.0.7 on 2026-09-09 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0015_alter_joblisting_skills'),
        ('events', '0002_calendarevent_all_day_calendarevent_end_time_and_more'),
        ('network', '0004_relationship_source_catalogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='applications.application'),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='applications.company'),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='people',
            field=models.ManyToManyField(blank=True, related_name='events', to='network.person'),
        ),
    ]
