# Generated by Django 6.0.7 on 2026-09-07 06:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0003_resume_application_resume_and_more'),
        ('network', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('done', 'Done'), ('cancelled', 'Cancelled')], default='open', max_length=12)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='todos', to='applications.application')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='todos', to='applications.company')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='todos', to='network.person')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['status', 'due_date', '-priority'],
                'indexes': [models.Index(fields=['user', 'status', 'due_date'], name='todos_todo_user_id_6bc66b_idx'), models.Index(fields=['completed_at'], name='todos_todo_complet_4c1d37_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('status__in', ['open', 'done', 'cancelled'])), name='valid_todo_status'), models.CheckConstraint(condition=models.Q(('priority__in', ['low', 'medium', 'high'])), name='valid_todo_priority'), models.CheckConstraint(condition=models.Q(models.Q(('completed_at__isnull', False), ('status', 'done')), models.Q(('status', 'done'), _negated=True), _connector='OR'), name='done_todo_has_completed_at')],
            },
        ),
    ]
