# Generated by Django 6.0.7 on 2026-09-13 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0003_todo_due_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='due_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
