# Generated by Django 6.0.7 on 2026-09-26 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0004_todo_due_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='google_task_id',
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
    ]
