# Generated by Django 6.0.7 on 2026-09-07 15:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('network', '0002_person_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Catchup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('met_on', models.DateField()),
                ('title', models.CharField(blank=True, max_length=255)),
                ('format', models.CharField(choices=[('coffee', 'Coffee / in person'), ('call', 'Phone call'), ('video', 'Video call'), ('event', 'Event / conference'), ('message', 'Messages'), ('other', 'Other')], default='coffee', max_length=20)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('minutes', models.TextField(blank=True)),
                ('takeaways', models.TextField(blank=True)),
                ('follow_up_on', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catchups', to='network.person')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catchups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-met_on', '-created_at'],
                'indexes': [models.Index(fields=['user', 'met_on'], name='catchups_ca_user_id_df7fd0_idx'), models.Index(fields=['person', 'met_on'], name='catchups_ca_person__9ea06d_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('format__in', ['coffee', 'call', 'video', 'event', 'message', 'other'])), name='valid_catchup_format'), models.CheckConstraint(condition=models.Q(('follow_up_on__isnull', True), ('follow_up_on__gte', models.F('met_on')), _connector='OR'), name='followup_not_before_meeting')],
            },
        ),
    ]
