# Generated by Django 6.0.7 on 2026-09-08 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catchups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='catchup',
            name='format_other',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
