# Generated by Django 6.0.7 on 2026-09-13 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catchups', '0003_title_case_format_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='catchup',
            name='message_channel',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
