# Generated by Django 6.0.7 on 2026-09-26 02:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleTasksConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refresh_token', models.TextField(blank=True)),
                ('access_token', models.TextField(blank=True)),
                ('access_token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('tasklist_id', models.CharField(blank=True, max_length=255)),
                ('pending_state', models.CharField(blank=True, max_length=64)),
                ('pending_verifier', models.CharField(blank=True, max_length=128)),
                ('pending_redirect_uri', models.CharField(blank=True, max_length=255)),
                ('connected_at', models.DateTimeField(blank=True, null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='google_tasks_connection', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
