# Generated by Django 6.0.7 on 2026-09-07 06:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0003_resume_application_resume_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('lead', 'Lead'), ('connection', 'Connection'), ('archived', 'Archived'), ('ghosted', 'Ghosted')], default='lead', max_length=20)),
                ('relationship', models.CharField(choices=[('mentor', 'Mentor'), ('alumni', 'Alumni'), ('classmate', 'Classmate'), ('colleague', 'Colleague'), ('manager', 'Manager'), ('recruiter', 'Recruiter'), ('interviewer', 'Interviewer'), ('industry_contact', 'Industry contact'), ('academic', 'Academic'), ('other', 'Other')], default='other', max_length=30)),
                ('source', models.CharField(choices=[('university_event', 'University event'), ('professional_event', 'Professional event'), ('internship', 'Internship'), ('workplace', 'Workplace'), ('class', 'Class'), ('referral', 'Referral'), ('linkedin', 'LinkedIn'), ('other', 'Other')], default='other', max_length=30)),
                ('last_meeting_at', models.DateField(blank=True, null=True)),
                ('next_chat_at', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applications', models.ManyToManyField(blank=True, related_name='people', to='applications.application')),
                ('companies', models.ManyToManyField(blank=True, related_name='people', to='applications.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='people', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'people',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='ContactMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('linkedin', 'LinkedIn'), ('email', 'Email'), ('whatsapp', 'WhatsApp'), ('phone', 'Phone'), ('instagram', 'Instagram'), ('other', 'Other')], max_length=20)),
                ('value', models.CharField(max_length=255)),
                ('is_preferred', models.BooleanField(default=False)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_methods', to='network.person')),
            ],
            options={
                'ordering': ['-is_preferred', 'channel'],
            },
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['user', 'status'], name='network_per_user_id_7d023a_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['next_chat_at'], name='network_per_next_ch_7bc999_idx'),
        ),
        migrations.AddConstraint(
            model_name='person',
            constraint=models.UniqueConstraint(fields=('user', 'full_name'), name='uniq_person_name_per_user'),
        ),
        migrations.AddConstraint(
            model_name='person',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['lead', 'connection', 'archived', 'ghosted'])), name='valid_person_status'),
        ),
        migrations.AddConstraint(
            model_name='person',
            constraint=models.CheckConstraint(condition=models.Q(('relationship__in', ['mentor', 'alumni', 'classmate', 'colleague', 'manager', 'recruiter', 'interviewer', 'industry_contact', 'academic', 'other'])), name='valid_person_relationship'),
        ),
        migrations.AddConstraint(
            model_name='person',
            constraint=models.CheckConstraint(condition=models.Q(('source__in', ['university_event', 'professional_event', 'internship', 'workplace', 'class', 'referral', 'linkedin', 'other'])), name='valid_person_source'),
        ),
        migrations.AddConstraint(
            model_name='contactmethod',
            constraint=models.UniqueConstraint(fields=('person', 'channel', 'value'), name='uniq_contact_per_person'),
        ),
        migrations.AddConstraint(
            model_name='contactmethod',
            constraint=models.CheckConstraint(condition=models.Q(('channel__in', ['linkedin', 'email', 'whatsapp', 'phone', 'instagram', 'other'])), name='valid_contact_channel'),
        ),
    ]
