# Generated by Django 6.0.7 on 2026-09-08 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_person_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='cadence_months',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
