import django.db.models.deletion
from django.db import migrations, models


def copy_memberships(apps, schema_editor):
    """Carry the existing flat person↔company pairs into the through table.

    Runs *before* the AlterField below, which drops the auto-created join
    table. Every copied row lands with no dates and `is_current` null — which
    the `is_past` rule reads as "current, never said otherwise", so nothing
    the user already entered suddenly renders as a past employer.
    """
    Person = apps.get_model("network", "Person")
    PersonCompany = apps.get_model("network", "PersonCompany")

    rows = [
        PersonCompany(person=person, company=company)
        for person in Person.objects.prefetch_related("companies")
        for company in person.companies.all()
    ]
    PersonCompany.objects.bulk_create(rows, ignore_conflicts=True)


def drop_memberships(apps, schema_editor):
    apps.get_model("network", "PersonCompany").objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0017_applicationdocument'),
        ('network', '0004_relationship_source_catalogs'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('started_on', models.DateField(blank=True, null=True)),
                ('ended_on', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_links', to='applications.company')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_links', to='network.person')),
            ],
            options={
                'ordering': ['-started_on', '-id'],
            },
        ),
        migrations.RunPython(copy_memberships, drop_memberships),
        # Django refuses to add `through=` to a live M2M with a plain
        # AlterField ("you cannot ... add or remove through= on M2M fields"),
        # so the state change and the database change are made separately:
        # Django learns about the through model, and the now-redundant
        # auto-created join table is dropped by hand.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name='person',
                    name='companies',
                    field=models.ManyToManyField(blank=True, related_name='people', through='network.PersonCompany', to='applications.company'),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql="DROP TABLE network_person_companies;",
                    reverse_sql="""
                        CREATE TABLE network_person_companies (
                            id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            person_id bigint NOT NULL REFERENCES network_person(id) DEFERRABLE INITIALLY DEFERRED,
                            company_id bigint NOT NULL REFERENCES applications_company(id) DEFERRABLE INITIALLY DEFERRED,
                            CONSTRAINT network_person_companies_person_id_company_id_uniq UNIQUE (person_id, company_id)
                        );
                        INSERT INTO network_person_companies (person_id, company_id)
                        SELECT person_id, company_id FROM network_personcompany;
                    """,
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name='personcompany',
            constraint=models.UniqueConstraint(fields=('person', 'company'), name='uniq_person_company'),
        ),
        migrations.AddConstraint(
            model_name='personcompany',
            constraint=models.CheckConstraint(condition=models.Q(('ended_on__isnull', True), ('started_on__isnull', True), ('ended_on__gte', models.F('started_on')), _connector='OR'), name='person_company_ends_after_it_starts'),
        ),
    ]
