# Generated by Django 6.0.7 on 2026-09-10 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_person_company_through'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='connections',
            field=models.ManyToManyField(blank=True, to='network.person'),
        ),
    ]
