# Generated by Django 6.0.7 on 2026-09-13 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_title_case_relationship_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='last_message_channel',
            field=models.CharField(blank=True, choices=[('linkedin', 'LinkedIn'), ('email', 'Email'), ('sms', 'Text / WhatsApp'), ('other', 'Other')], max_length=20),
        ),
        migrations.AddField(
            model_name='person',
            name='last_messaged_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
