# Generated by Django 6.0.7 on 2026-08-18 06:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'companies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name_plural': 'countries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name_plural': 'industries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['state__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('not_submitted', 'Not submitted'), ('applied', 'Applied'), ('online_assessment', 'Online assessment'), ('video_interview', 'Video interview'), ('assessment_centre', 'Assessment centre'), ('final_interview', 'Final interview'), ('offer', 'Offer')], default='applied', max_length=50)),
                ('outcome', models.CharField(choices=[('in_progress', 'In progress'), ('rejected', 'Rejected'), ('offer_received', 'Offer received'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('withdrawn', 'Withdrawn'), ('ghosted', 'Ghosted')], default='in_progress', max_length=50)),
                ('applied_at', models.DateField(default=django.utils.timezone.localdate)),
                ('source', models.CharField(blank=True, max_length=100)),
                ('resume_version', models.CharField(blank=True, max_length=100)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('stage_updated_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='applications.company')),
            ],
            options={
                'ordering': ['-applied_at', 'company__name'],
            },
        ),
        migrations.AddField(
            model_name='company',
            name='industry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to='applications.industry'),
        ),
        migrations.CreateModel(
            name='JobListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_type', models.CharField(blank=True, choices=[('vacationer', 'Vacationer / Internship'), ('graduate', 'Graduate'), ('undergraduate', 'Undergraduate'), ('side_job', 'Side job')], max_length=50)),
                ('work_arrangement', models.CharField(blank=True, choices=[('full_time', 'Full-time'), ('part_time', 'Part-time'), ('casual', 'Casual'), ('contract', 'Contract')], max_length=50)),
                ('opened_at', models.DateField(blank=True, null=True)),
                ('closing_at', models.DateField(blank=True, null=True)),
                ('job_url', models.URLField(blank=True, max_length=255, null=True, unique=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='applications.company')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='applications.location')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='applications.role')),
            ],
            options={
                'ordering': ['company__name', 'role__name'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationJobListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome', models.CharField(blank=True, choices=[('in_progress', 'In progress'), ('rejected', 'Rejected'), ('offer_received', 'Offer received'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('withdrawn', 'Withdrawn'), ('ghosted', 'Ghosted')], help_text="Leave blank unless this role's result differs from the application.", max_length=50)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listing_links', to='applications.application')),
                ('job_listing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='application_links', to='applications.joblisting')),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='listings',
            field=models.ManyToManyField(related_name='applications', through='applications.ApplicationJobListing', to='applications.joblisting'),
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='states', to='applications.country')),
            ],
            options={
                'ordering': ['country__name', 'name'],
            },
        ),
        migrations.AddField(
            model_name='location',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='locations', to='applications.state'),
        ),
        migrations.CreateModel(
            name='AppsEventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prev_stage', models.CharField(blank=True, choices=[('not_submitted', 'Not submitted'), ('applied', 'Applied'), ('online_assessment', 'Online assessment'), ('video_interview', 'Video interview'), ('assessment_centre', 'Assessment centre'), ('final_interview', 'Final interview'), ('offer', 'Offer')], max_length=50)),
                ('curr_stage', models.CharField(choices=[('not_submitted', 'Not submitted'), ('applied', 'Applied'), ('online_assessment', 'Online assessment'), ('video_interview', 'Video interview'), ('assessment_centre', 'Assessment centre'), ('final_interview', 'Final interview'), ('offer', 'Offer')], max_length=50)),
                ('prev_outcome', models.CharField(blank=True, choices=[('in_progress', 'In progress'), ('rejected', 'Rejected'), ('offer_received', 'Offer received'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('withdrawn', 'Withdrawn'), ('ghosted', 'Ghosted')], max_length=50)),
                ('curr_outcome', models.CharField(choices=[('in_progress', 'In progress'), ('rejected', 'Rejected'), ('offer_received', 'Offer received'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('withdrawn', 'Withdrawn'), ('ghosted', 'Ghosted')], max_length=50)),
                ('changed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('note', models.TextField(blank=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_logs', to='applications.application')),
            ],
            options={
                'ordering': ['application', 'changed_at'],
                'constraints': [models.UniqueConstraint(fields=('application', 'changed_at'), name='uniq_event_per_app_time')],
            },
        ),
        migrations.AddConstraint(
            model_name='company',
            constraint=models.UniqueConstraint(fields=('name',), name='uniq_company_name'),
        ),
        migrations.AddConstraint(
            model_name='applicationjoblisting',
            constraint=models.UniqueConstraint(fields=('application', 'job_listing'), name='uniq_application_listing'),
        ),
        migrations.AddConstraint(
            model_name='applicationjoblisting',
            constraint=models.CheckConstraint(condition=models.Q(('outcome__in', ['in_progress', 'rejected', 'offer_received', 'accepted', 'declined', 'withdrawn', 'ghosted']), ('outcome', ''), _connector='OR'), name='valid_role_outcome'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['user', 'company', 'applied_at'], name='application_user_id_8ca650_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['stage'], name='application_stage_264235_idx'),
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.CheckConstraint(condition=models.Q(('stage__in', ['not_submitted', 'applied', 'online_assessment', 'video_interview', 'assessment_centre', 'final_interview', 'offer'])), name='valid_stage'),
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.CheckConstraint(condition=models.Q(('outcome__in', ['in_progress', 'rejected', 'offer_received', 'accepted', 'declined', 'withdrawn', 'ghosted'])), name='valid_outcome'),
        ),
        migrations.AddConstraint(
            model_name='joblisting',
            constraint=models.UniqueConstraint(fields=('company', 'role', 'location', 'opened_at'), name='uniq_job_listing'),
        ),
        migrations.AddConstraint(
            model_name='joblisting',
            constraint=models.CheckConstraint(condition=models.Q(('role_type__in', ['vacationer', 'graduate', 'undergraduate', 'side_job']), ('role_type', ''), _connector='OR'), name='valid_role_type'),
        ),
        migrations.AddConstraint(
            model_name='joblisting',
            constraint=models.CheckConstraint(condition=models.Q(('work_arrangement__in', ['full_time', 'part_time', 'casual', 'contract']), ('work_arrangement', ''), _connector='OR'), name='valid_work_arrangement'),
        ),
        migrations.AddConstraint(
            model_name='state',
            constraint=models.UniqueConstraint(fields=('country', 'name'), name='uniq_state_per_country'),
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.UniqueConstraint(fields=('state', 'name'), name='uniq_location_per_state'),
        ),
    ]
