# Generated by Django 6.0.7 on 2026-09-05 05:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_delete_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('variant_type', models.CharField(choices=[('general', 'General'), ('company', 'Company-specific'), ('role', 'Role-specific')], default='general', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_companies', models.ManyToManyField(blank=True, related_name='tailored_resumes', to='applications.company')),
                ('target_roles', models.ManyToManyField(blank=True, related_name='tailored_resumes', to='applications.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='application',
            name='resume',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='applications.resume'),
        ),
        migrations.AddConstraint(
            model_name='resume',
            constraint=models.UniqueConstraint(fields=('user', 'label'), name='uniq_resume_label_per_user'),
        ),
        migrations.AddConstraint(
            model_name='resume',
            constraint=models.CheckConstraint(condition=models.Q(('variant_type__in', ['general', 'company', 'role'])), name='valid_resume_variant_type'),
        ),
    ]
