# Generated by Django 6.0.7 on 2026-09-07 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_company_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='appseventlog',
            name='changes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='appseventlog',
            name='event_type',
            field=models.CharField(choices=[('created', 'Created'), ('stage', 'Stage change'), ('outcome', 'Outcome change'), ('edited', 'Edited')], default='edited', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='appseventlog',
            constraint=models.CheckConstraint(condition=models.Q(('event_type__in', ['created', 'stage', 'outcome', 'edited'])), name='valid_event_type'),
        ),
    ]
