# Generated by Django 6.0.7 on 2026-09-07 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_backfill_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
        migrations.AddField(
            model_name='resume',
            name='file_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
