# Generated by Django 6.0.7 on 2026-09-07 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0007_resume_file_resume_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='reapply_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
