# Generated by Django 6.0.7 on 2026-09-08 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0008_application_reapply_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='short_name',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
