# Generated by Django 6.0.7 on 2026-09-08 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0009_company_short_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='regions',
            field=models.ManyToManyField(blank=True, related_name='companies_in_region', to='applications.country'),
        ),
    ]
