# Generated by Django 6.0.7 on 2026-09-08 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0010_company_regions'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblisting',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='skills',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
