# Generated by Django 6.0.7 on 2026-09-08 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0013_company_industries_m2m'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='venues', to='applications.location')),
            ],
            options={
                'ordering': ['location__name', 'name'],
                'constraints': [models.UniqueConstraint(fields=('location', 'name'), name='uniq_venue_per_location')],
            },
        ),
    ]
