# Generated by Django 6.0.7 on 2026-09-09 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0014_venue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblisting',
            name='skills',
            field=models.TextField(blank=True),
        ),
    ]
