# Generated by Django 6.0.7 on 2026-09-10 04:27

from django.db import migrations, models

# The seven the app shipped with, keyed exactly as `Application.stage` already
# stores them — so every existing row keeps its stage without being touched.
PRESETS = [
    ("not_submitted", "Not submitted"),
    ("applied", "Applied"),
    ("online_assessment", "Online assessment"),
    ("video_interview", "Video interview"),
    ("assessment_centre", "Assessment centre"),
    ("final_interview", "Final interview"),
    ("offer", "Offer"),
]


def seed_presets(apps, schema_editor):
    Stage = apps.get_model("applications", "ApplicationStage")
    for position, (key, name) in enumerate(PRESETS):
        Stage.objects.get_or_create(
            key=key, defaults={"name": name, "position": position, "is_preset": True}
        )


def drop_presets(apps, schema_editor):
    Stage = apps.get_model("applications", "ApplicationStage")
    Stage.objects.filter(key__in=[key for key, _ in PRESETS]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0015_alter_joblisting_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=50)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('is_preset', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='application',
            name='valid_stage',
        ),
        migrations.RunPython(seed_presets, drop_presets),
    ]
