# Generated by Django 6.0.7 on 2026-09-10 14:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0017_applicationdocument'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='resume',
            constraint=models.UniqueConstraint(condition=models.Q(('file_name', ''), _negated=True), fields=('user', 'file_name'), name='uniq_resume_file_name_per_user'),
        ),
    ]
