# Generated by Django 6.0.7 on 2026-09-10 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0018_resume_file_name_unique_per_user'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='appseventlog',
            name='valid_event_type',
        ),
        migrations.AddField(
            model_name='application',
            name='awaiting_response',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='awaiting_since',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='is_historical',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='appseventlog',
            name='event_type',
            field=models.CharField(choices=[('created', 'Created'), ('stage', 'Stage change'), ('outcome', 'Outcome change'), ('edited', 'Edited'), ('waiting_started', 'Waiting for response'), ('waiting_ended', 'Response received')], default='edited', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='appseventlog',
            constraint=models.CheckConstraint(condition=models.Q(('event_type__in', ['created', 'stage', 'outcome', 'edited', 'waiting_started', 'waiting_ended'])), name='valid_event_type'),
        ),
    ]
