# Generated by Django 6.0.7 on 2026-09-13 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0022_library_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='librarydocument',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='library_documents', to='applications.company'),
        ),
    ]
