# Generated by Django 6.0.7 on 2026-09-13 15:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0023_library_document_company'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='application',
            name='valid_outcome',
        ),
        migrations.RemoveConstraint(
            model_name='applicationjoblisting',
            name='valid_role_outcome',
        ),
        migrations.AlterField(
            model_name='application',
            name='outcome',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('rejected', 'Rejected'), ('offer_received', 'Offer Received'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('withdrawn', 'Withdrawn'), ('ghosted', 'Ghosted'), ('missed_deadline', 'Missed Deadline')], default='in_progress', max_length=50),
        ),
        migrations.AlterField(
            model_name='applicationjoblisting',
            name='outcome',
            field=models.CharField(blank=True, choices=[('in_progress', 'In Progress'), ('rejected', 'Rejected'), ('offer_received', 'Offer Received'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('withdrawn', 'Withdrawn'), ('ghosted', 'Ghosted'), ('missed_deadline', 'Missed Deadline')], help_text="Leave blank unless this role's result differs from the application.", max_length=50),
        ),
        migrations.AlterField(
            model_name='appseventlog',
            name='curr_outcome',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('rejected', 'Rejected'), ('offer_received', 'Offer Received'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('withdrawn', 'Withdrawn'), ('ghosted', 'Ghosted'), ('missed_deadline', 'Missed Deadline')], max_length=50),
        ),
        migrations.AlterField(
            model_name='appseventlog',
            name='prev_outcome',
            field=models.CharField(blank=True, choices=[('in_progress', 'In Progress'), ('rejected', 'Rejected'), ('offer_received', 'Offer Received'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('withdrawn', 'Withdrawn'), ('ghosted', 'Ghosted'), ('missed_deadline', 'Missed Deadline')], max_length=50),
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.CheckConstraint(condition=models.Q(('outcome__in', ['in_progress', 'rejected', 'offer_received', 'accepted', 'declined', 'withdrawn', 'ghosted', 'missed_deadline'])), name='valid_outcome'),
        ),
        migrations.AddConstraint(
            model_name='applicationjoblisting',
            constraint=models.CheckConstraint(condition=models.Q(('outcome__in', ['in_progress', 'rejected', 'offer_received', 'accepted', 'declined', 'withdrawn', 'ghosted', 'missed_deadline']), ('outcome', ''), _connector='OR'), name='valid_role_outcome'),
        ),
    ]
