# Generated by Django 6.0.7 on 2026-09-14 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0025_stage_missed_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='stage',
            field=models.CharField(choices=[('not_submitted', 'Not Submitted'), ('applied', 'Applied'), ('online_assessment', 'Online Assessment'), ('video_interview', 'Video Interview'), ('assessment_centre', 'Assessment Center'), ('final_interview', 'Final Interview'), ('offer', 'Offer'), ('missed_deadline', 'Missed Deadline')], default='applied', max_length=50),
        ),
        migrations.AlterField(
            model_name='appseventlog',
            name='curr_stage',
            field=models.CharField(choices=[('not_submitted', 'Not Submitted'), ('applied', 'Applied'), ('online_assessment', 'Online Assessment'), ('video_interview', 'Video Interview'), ('assessment_centre', 'Assessment Center'), ('final_interview', 'Final Interview'), ('offer', 'Offer'), ('missed_deadline', 'Missed Deadline')], max_length=50),
        ),
        migrations.AlterField(
            model_name='appseventlog',
            name='prev_stage',
            field=models.CharField(blank=True, choices=[('not_submitted', 'Not Submitted'), ('applied', 'Applied'), ('online_assessment', 'Online Assessment'), ('video_interview', 'Video Interview'), ('assessment_centre', 'Assessment Center'), ('final_interview', 'Final Interview'), ('offer', 'Offer'), ('missed_deadline', 'Missed Deadline')], max_length=50),
        ),
    ]
