# Generated by Django 6.0.7 on 2026-09-08 12:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleDataRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('application', 'Sample applications'), ('todo', 'Sample todos'), ('catchup', 'Sample coffee chats'), ('person', 'Sample contact'), ('event', 'Sample calendar event')], max_length=20)),
                ('object_id', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sample_data_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['category', 'id'],
                'indexes': [models.Index(fields=['user', 'category'], name='onboarding__user_id_1e0484_idx')],
            },
        ),
    ]
